### ISSUE TITLE
Improving tokenization/entity recognition results

### ISSUE THREAD

**Issue by itaim** [philschmid/advanced-pii-huggingface-sagemaker#1]
Hi @philschmid ,
Thank you very much for this repo.
I tested it on some data for the most part it does a good job but occasionally it inserts duplicate entities and I was wondering what could be done to improve this?

Some examples:
Text is:
```
Hey Denny,

That's strange, but thanks for sending the second email. Confirming that
Acme Safety Net was enabled for the new portfolio, and we did not freeze
device modifiers for the other NB portfolios so I did not do it for the new
one.

Thanks!


Best,

Tiffany Smith

*Senior Client Success Manager, Search* | Acme

Pronouns: she, her

m: 415 806 1111

w: www.acme.com l: LinkedIn
<[Link]>
```

Result is:
```
Hey <PERSON>,<PERSON>That's strange, but thanks for sending the second email. Confirming that
Acme Safety Net was enabled for the new portfolio, and we did not freeze
device modifiers for the other NB portfolios so I did not do it for the new
one.<PERSON>Thanks!<PERSON>
Best,<PERSON><PERSON>*Senior Client Success Manager, Search* | <ORGANIZATION>
Pronouns: she, her

m: <PHONE_NUMBER>

w: <URL> l: <ORGANIZATION>
<[Link]>
```

So in this example there are `<PERSON>` tokens inserted for no apparent reason.
Also `Acme Safety` was not anonymized into `<ORGANIZATION> Safety` or `<ORGANIZATION>` as expected.
It also appears that these extra `<PERSON>` tokens are inserted instead of line breaks in the text.

Like I said, these glitches occur occasionally and for the most part results are accurate.

**Comment by itaim** [comment]
I replaced `\n\`n` with `\n` and it fixed it.

**Comment by philschmid** [comment]
I am glad you managed to fix it. But in addition what else you could to do is adjust the [aggregation_strategy](https://github.com/philschmid/advanced-pii-huggingface-sagemaker/blob/ab9c9a4b22006a64eeed059c80dff55540f8dcf8/code/inference.py#L38) to a different one. You can read more in the [documentation](https://huggingface.co/docs/transformers/v4.19.3/en/main_classes/pipelines#transformers.TokenClassificationPipeline.aggregation_strategy) this can also help "concat" entities.
